/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard/users'
import { Route as DashboardSubmissionsRouteImport } from './routes/_dashboard/submissions'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardHelpRouteImport } from './routes/_dashboard/help'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardCmsIndexRouteImport } from './routes/_dashboard/cms/index'
import { Route as DashboardSchoolSettingsRouteImport } from './routes/_dashboard/school/settings'
import { Route as DashboardSchoolFeesRouteImport } from './routes/_dashboard/school/fees'
import { Route as DashboardSchoolExtraChargesRouteImport } from './routes/_dashboard/school/extra-charges'
import { Route as DashboardCmsPageIdRouteImport } from './routes/_dashboard/cms/$pageId'
import { Route as DashboardSchoolTermsIndexRouteImport } from './routes/_dashboard/school/terms/index'
import { Route as DashboardSchoolSubjectsIndexRouteImport } from './routes/_dashboard/school/subjects/index'
import { Route as DashboardSchoolStudentsIndexRouteImport } from './routes/_dashboard/school/students/index'
import { Route as DashboardSchoolStaffIndexRouteImport } from './routes/_dashboard/school/staff/index'
import { Route as DashboardSchoolReportsIndexRouteImport } from './routes/_dashboard/school/reports/index'
import { Route as DashboardSchoolGradesIndexRouteImport } from './routes/_dashboard/school/grades/index'
import { Route as DashboardSchoolExamsIndexRouteImport } from './routes/_dashboard/school/exams/index'
import { Route as DashboardSchoolStudentsIdRouteImport } from './routes/_dashboard/school/students/$id'
import { Route as DashboardSchoolStaffIdRouteImport } from './routes/_dashboard/school/staff/$id'
import { Route as DashboardSchoolReportsFeesRouteImport } from './routes/_dashboard/school/reports/fees'
import { Route as DashboardSchoolExamsIdRouteImport } from './routes/_dashboard/school/exams/$id'
import { Route as DashboardSchoolReportsStudentsStudentIdRouteImport } from './routes/_dashboard/school/reports/students/$studentId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSubmissionsRoute = DashboardSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCmsIndexRoute = DashboardCmsIndexRouteImport.update({
  id: '/cms/',
  path: '/cms/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchoolSettingsRoute = DashboardSchoolSettingsRouteImport.update({
  id: '/school/settings',
  path: '/school/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchoolFeesRoute = DashboardSchoolFeesRouteImport.update({
  id: '/school/fees',
  path: '/school/fees',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchoolExtraChargesRoute =
  DashboardSchoolExtraChargesRouteImport.update({
    id: '/school/extra-charges',
    path: '/school/extra-charges',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCmsPageIdRoute = DashboardCmsPageIdRouteImport.update({
  id: '/cms/$pageId',
  path: '/cms/$pageId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchoolTermsIndexRoute =
  DashboardSchoolTermsIndexRouteImport.update({
    id: '/school/terms/',
    path: '/school/terms/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSchoolSubjectsIndexRoute =
  DashboardSchoolSubjectsIndexRouteImport.update({
    id: '/school/subjects/',
    path: '/school/subjects/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSchoolStudentsIndexRoute =
  DashboardSchoolStudentsIndexRouteImport.update({
    id: '/school/students/',
    path: '/school/students/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSchoolStaffIndexRoute =
  DashboardSchoolStaffIndexRouteImport.update({
    id: '/school/staff/',
    path: '/school/staff/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSchoolReportsIndexRoute =
  DashboardSchoolReportsIndexRouteImport.update({
    id: '/school/reports/',
    path: '/school/reports/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSchoolGradesIndexRoute =
  DashboardSchoolGradesIndexRouteImport.update({
    id: '/school/grades/',
    path: '/school/grades/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSchoolExamsIndexRoute =
  DashboardSchoolExamsIndexRouteImport.update({
    id: '/school/exams/',
    path: '/school/exams/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSchoolStudentsIdRoute =
  DashboardSchoolStudentsIdRouteImport.update({
    id: '/school/students/$id',
    path: '/school/students/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSchoolStaffIdRoute = DashboardSchoolStaffIdRouteImport.update({
  id: '/school/staff/$id',
  path: '/school/staff/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchoolReportsFeesRoute =
  DashboardSchoolReportsFeesRouteImport.update({
    id: '/school/reports/fees',
    path: '/school/reports/fees',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSchoolExamsIdRoute = DashboardSchoolExamsIdRouteImport.update({
  id: '/school/exams/$id',
  path: '/school/exams/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchoolReportsStudentsStudentIdRoute =
  DashboardSchoolReportsStudentsStudentIdRouteImport.update({
    id: '/school/reports/students/$studentId',
    path: '/school/reports/students/$studentId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/help': typeof DashboardHelpRoute
  '/profile': typeof DashboardProfileRoute
  '/submissions': typeof DashboardSubmissionsRoute
  '/users': typeof DashboardUsersRoute
  '/cms/$pageId': typeof DashboardCmsPageIdRoute
  '/school/extra-charges': typeof DashboardSchoolExtraChargesRoute
  '/school/fees': typeof DashboardSchoolFeesRoute
  '/school/settings': typeof DashboardSchoolSettingsRoute
  '/cms/': typeof DashboardCmsIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/school/exams/$id': typeof DashboardSchoolExamsIdRoute
  '/school/reports/fees': typeof DashboardSchoolReportsFeesRoute
  '/school/staff/$id': typeof DashboardSchoolStaffIdRoute
  '/school/students/$id': typeof DashboardSchoolStudentsIdRoute
  '/school/exams/': typeof DashboardSchoolExamsIndexRoute
  '/school/grades/': typeof DashboardSchoolGradesIndexRoute
  '/school/reports/': typeof DashboardSchoolReportsIndexRoute
  '/school/staff/': typeof DashboardSchoolStaffIndexRoute
  '/school/students/': typeof DashboardSchoolStudentsIndexRoute
  '/school/subjects/': typeof DashboardSchoolSubjectsIndexRoute
  '/school/terms/': typeof DashboardSchoolTermsIndexRoute
  '/school/reports/students/$studentId': typeof DashboardSchoolReportsStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/help': typeof DashboardHelpRoute
  '/profile': typeof DashboardProfileRoute
  '/submissions': typeof DashboardSubmissionsRoute
  '/users': typeof DashboardUsersRoute
  '/cms/$pageId': typeof DashboardCmsPageIdRoute
  '/school/extra-charges': typeof DashboardSchoolExtraChargesRoute
  '/school/fees': typeof DashboardSchoolFeesRoute
  '/school/settings': typeof DashboardSchoolSettingsRoute
  '/cms': typeof DashboardCmsIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/school/exams/$id': typeof DashboardSchoolExamsIdRoute
  '/school/reports/fees': typeof DashboardSchoolReportsFeesRoute
  '/school/staff/$id': typeof DashboardSchoolStaffIdRoute
  '/school/students/$id': typeof DashboardSchoolStudentsIdRoute
  '/school/exams': typeof DashboardSchoolExamsIndexRoute
  '/school/grades': typeof DashboardSchoolGradesIndexRoute
  '/school/reports': typeof DashboardSchoolReportsIndexRoute
  '/school/staff': typeof DashboardSchoolStaffIndexRoute
  '/school/students': typeof DashboardSchoolStudentsIndexRoute
  '/school/subjects': typeof DashboardSchoolSubjectsIndexRoute
  '/school/terms': typeof DashboardSchoolTermsIndexRoute
  '/school/reports/students/$studentId': typeof DashboardSchoolReportsStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/help': typeof DashboardHelpRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/submissions': typeof DashboardSubmissionsRoute
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/cms/$pageId': typeof DashboardCmsPageIdRoute
  '/_dashboard/school/extra-charges': typeof DashboardSchoolExtraChargesRoute
  '/_dashboard/school/fees': typeof DashboardSchoolFeesRoute
  '/_dashboard/school/settings': typeof DashboardSchoolSettingsRoute
  '/_dashboard/cms/': typeof DashboardCmsIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/school/exams/$id': typeof DashboardSchoolExamsIdRoute
  '/_dashboard/school/reports/fees': typeof DashboardSchoolReportsFeesRoute
  '/_dashboard/school/staff/$id': typeof DashboardSchoolStaffIdRoute
  '/_dashboard/school/students/$id': typeof DashboardSchoolStudentsIdRoute
  '/_dashboard/school/exams/': typeof DashboardSchoolExamsIndexRoute
  '/_dashboard/school/grades/': typeof DashboardSchoolGradesIndexRoute
  '/_dashboard/school/reports/': typeof DashboardSchoolReportsIndexRoute
  '/_dashboard/school/staff/': typeof DashboardSchoolStaffIndexRoute
  '/_dashboard/school/students/': typeof DashboardSchoolStudentsIndexRoute
  '/_dashboard/school/subjects/': typeof DashboardSchoolSubjectsIndexRoute
  '/_dashboard/school/terms/': typeof DashboardSchoolTermsIndexRoute
  '/_dashboard/school/reports/students/$studentId': typeof DashboardSchoolReportsStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/help'
    | '/profile'
    | '/submissions'
    | '/users'
    | '/cms/$pageId'
    | '/school/extra-charges'
    | '/school/fees'
    | '/school/settings'
    | '/cms/'
    | '/settings/'
    | '/school/exams/$id'
    | '/school/reports/fees'
    | '/school/staff/$id'
    | '/school/students/$id'
    | '/school/exams/'
    | '/school/grades/'
    | '/school/reports/'
    | '/school/staff/'
    | '/school/students/'
    | '/school/subjects/'
    | '/school/terms/'
    | '/school/reports/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/help'
    | '/profile'
    | '/submissions'
    | '/users'
    | '/cms/$pageId'
    | '/school/extra-charges'
    | '/school/fees'
    | '/school/settings'
    | '/cms'
    | '/settings'
    | '/school/exams/$id'
    | '/school/reports/fees'
    | '/school/staff/$id'
    | '/school/students/$id'
    | '/school/exams'
    | '/school/grades'
    | '/school/reports'
    | '/school/staff'
    | '/school/students'
    | '/school/subjects'
    | '/school/terms'
    | '/school/reports/students/$studentId'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/about'
    | '/_auth/login'
    | '/_dashboard/help'
    | '/_dashboard/profile'
    | '/_dashboard/submissions'
    | '/_dashboard/users'
    | '/_dashboard/'
    | '/_dashboard/cms/$pageId'
    | '/_dashboard/school/extra-charges'
    | '/_dashboard/school/fees'
    | '/_dashboard/school/settings'
    | '/_dashboard/cms/'
    | '/_dashboard/settings/'
    | '/_dashboard/school/exams/$id'
    | '/_dashboard/school/reports/fees'
    | '/_dashboard/school/staff/$id'
    | '/_dashboard/school/students/$id'
    | '/_dashboard/school/exams/'
    | '/_dashboard/school/grades/'
    | '/_dashboard/school/reports/'
    | '/_dashboard/school/staff/'
    | '/_dashboard/school/students/'
    | '/_dashboard/school/subjects/'
    | '/_dashboard/school/terms/'
    | '/_dashboard/school/reports/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/submissions': {
      id: '/_dashboard/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof DashboardSubmissionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/help': {
      id: '/_dashboard/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/cms/': {
      id: '/_dashboard/cms/'
      path: '/cms'
      fullPath: '/cms/'
      preLoaderRoute: typeof DashboardCmsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/settings': {
      id: '/_dashboard/school/settings'
      path: '/school/settings'
      fullPath: '/school/settings'
      preLoaderRoute: typeof DashboardSchoolSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/fees': {
      id: '/_dashboard/school/fees'
      path: '/school/fees'
      fullPath: '/school/fees'
      preLoaderRoute: typeof DashboardSchoolFeesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/extra-charges': {
      id: '/_dashboard/school/extra-charges'
      path: '/school/extra-charges'
      fullPath: '/school/extra-charges'
      preLoaderRoute: typeof DashboardSchoolExtraChargesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/cms/$pageId': {
      id: '/_dashboard/cms/$pageId'
      path: '/cms/$pageId'
      fullPath: '/cms/$pageId'
      preLoaderRoute: typeof DashboardCmsPageIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/terms/': {
      id: '/_dashboard/school/terms/'
      path: '/school/terms'
      fullPath: '/school/terms/'
      preLoaderRoute: typeof DashboardSchoolTermsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/subjects/': {
      id: '/_dashboard/school/subjects/'
      path: '/school/subjects'
      fullPath: '/school/subjects/'
      preLoaderRoute: typeof DashboardSchoolSubjectsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/students/': {
      id: '/_dashboard/school/students/'
      path: '/school/students'
      fullPath: '/school/students/'
      preLoaderRoute: typeof DashboardSchoolStudentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/staff/': {
      id: '/_dashboard/school/staff/'
      path: '/school/staff'
      fullPath: '/school/staff/'
      preLoaderRoute: typeof DashboardSchoolStaffIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/reports/': {
      id: '/_dashboard/school/reports/'
      path: '/school/reports'
      fullPath: '/school/reports/'
      preLoaderRoute: typeof DashboardSchoolReportsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/grades/': {
      id: '/_dashboard/school/grades/'
      path: '/school/grades'
      fullPath: '/school/grades/'
      preLoaderRoute: typeof DashboardSchoolGradesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/exams/': {
      id: '/_dashboard/school/exams/'
      path: '/school/exams'
      fullPath: '/school/exams/'
      preLoaderRoute: typeof DashboardSchoolExamsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/students/$id': {
      id: '/_dashboard/school/students/$id'
      path: '/school/students/$id'
      fullPath: '/school/students/$id'
      preLoaderRoute: typeof DashboardSchoolStudentsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/staff/$id': {
      id: '/_dashboard/school/staff/$id'
      path: '/school/staff/$id'
      fullPath: '/school/staff/$id'
      preLoaderRoute: typeof DashboardSchoolStaffIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/reports/fees': {
      id: '/_dashboard/school/reports/fees'
      path: '/school/reports/fees'
      fullPath: '/school/reports/fees'
      preLoaderRoute: typeof DashboardSchoolReportsFeesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/exams/$id': {
      id: '/_dashboard/school/exams/$id'
      path: '/school/exams/$id'
      fullPath: '/school/exams/$id'
      preLoaderRoute: typeof DashboardSchoolExamsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/school/reports/students/$studentId': {
      id: '/_dashboard/school/reports/students/$studentId'
      path: '/school/reports/students/$studentId'
      fullPath: '/school/reports/students/$studentId'
      preLoaderRoute: typeof DashboardSchoolReportsStudentsStudentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSubmissionsRoute: typeof DashboardSubmissionsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCmsPageIdRoute: typeof DashboardCmsPageIdRoute
  DashboardSchoolExtraChargesRoute: typeof DashboardSchoolExtraChargesRoute
  DashboardSchoolFeesRoute: typeof DashboardSchoolFeesRoute
  DashboardSchoolSettingsRoute: typeof DashboardSchoolSettingsRoute
  DashboardCmsIndexRoute: typeof DashboardCmsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardSchoolExamsIdRoute: typeof DashboardSchoolExamsIdRoute
  DashboardSchoolReportsFeesRoute: typeof DashboardSchoolReportsFeesRoute
  DashboardSchoolStaffIdRoute: typeof DashboardSchoolStaffIdRoute
  DashboardSchoolStudentsIdRoute: typeof DashboardSchoolStudentsIdRoute
  DashboardSchoolExamsIndexRoute: typeof DashboardSchoolExamsIndexRoute
  DashboardSchoolGradesIndexRoute: typeof DashboardSchoolGradesIndexRoute
  DashboardSchoolReportsIndexRoute: typeof DashboardSchoolReportsIndexRoute
  DashboardSchoolStaffIndexRoute: typeof DashboardSchoolStaffIndexRoute
  DashboardSchoolStudentsIndexRoute: typeof DashboardSchoolStudentsIndexRoute
  DashboardSchoolSubjectsIndexRoute: typeof DashboardSchoolSubjectsIndexRoute
  DashboardSchoolTermsIndexRoute: typeof DashboardSchoolTermsIndexRoute
  DashboardSchoolReportsStudentsStudentIdRoute: typeof DashboardSchoolReportsStudentsStudentIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSubmissionsRoute: DashboardSubmissionsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCmsPageIdRoute: DashboardCmsPageIdRoute,
  DashboardSchoolExtraChargesRoute: DashboardSchoolExtraChargesRoute,
  DashboardSchoolFeesRoute: DashboardSchoolFeesRoute,
  DashboardSchoolSettingsRoute: DashboardSchoolSettingsRoute,
  DashboardCmsIndexRoute: DashboardCmsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardSchoolExamsIdRoute: DashboardSchoolExamsIdRoute,
  DashboardSchoolReportsFeesRoute: DashboardSchoolReportsFeesRoute,
  DashboardSchoolStaffIdRoute: DashboardSchoolStaffIdRoute,
  DashboardSchoolStudentsIdRoute: DashboardSchoolStudentsIdRoute,
  DashboardSchoolExamsIndexRoute: DashboardSchoolExamsIndexRoute,
  DashboardSchoolGradesIndexRoute: DashboardSchoolGradesIndexRoute,
  DashboardSchoolReportsIndexRoute: DashboardSchoolReportsIndexRoute,
  DashboardSchoolStaffIndexRoute: DashboardSchoolStaffIndexRoute,
  DashboardSchoolStudentsIndexRoute: DashboardSchoolStudentsIndexRoute,
  DashboardSchoolSubjectsIndexRoute: DashboardSchoolSubjectsIndexRoute,
  DashboardSchoolTermsIndexRoute: DashboardSchoolTermsIndexRoute,
  DashboardSchoolReportsStudentsStudentIdRoute:
    DashboardSchoolReportsStudentsStudentIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
