/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard/users'
import { Route as DashboardSubmissionsRouteImport } from './routes/_dashboard/submissions'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardCmsIndexRouteImport } from './routes/_dashboard/cms/index'
import { Route as DashboardCmsPageIdRouteImport } from './routes/_dashboard/cms/$pageId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSubmissionsRoute = DashboardSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardCmsIndexRoute = DashboardCmsIndexRouteImport.update({
  id: '/cms/',
  path: '/cms/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCmsPageIdRoute = DashboardCmsPageIdRouteImport.update({
  id: '/cms/$pageId',
  path: '/cms/$pageId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/profile': typeof DashboardProfileRoute
  '/settings': typeof DashboardSettingsRoute
  '/submissions': typeof DashboardSubmissionsRoute
  '/users': typeof DashboardUsersRoute
  '/cms/$pageId': typeof DashboardCmsPageIdRoute
  '/cms/': typeof DashboardCmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/profile': typeof DashboardProfileRoute
  '/settings': typeof DashboardSettingsRoute
  '/submissions': typeof DashboardSubmissionsRoute
  '/users': typeof DashboardUsersRoute
  '/cms/$pageId': typeof DashboardCmsPageIdRoute
  '/cms': typeof DashboardCmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/submissions': typeof DashboardSubmissionsRoute
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/cms/$pageId': typeof DashboardCmsPageIdRoute
  '/_dashboard/cms/': typeof DashboardCmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/settings'
    | '/submissions'
    | '/users'
    | '/cms/$pageId'
    | '/cms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/settings'
    | '/submissions'
    | '/users'
    | '/cms/$pageId'
    | '/cms'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/about'
    | '/_auth/login'
    | '/_dashboard/profile'
    | '/_dashboard/settings'
    | '/_dashboard/submissions'
    | '/_dashboard/users'
    | '/_dashboard/'
    | '/_dashboard/cms/$pageId'
    | '/_dashboard/cms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/submissions': {
      id: '/_dashboard/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof DashboardSubmissionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/cms/': {
      id: '/_dashboard/cms/'
      path: '/cms'
      fullPath: '/cms/'
      preLoaderRoute: typeof DashboardCmsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/cms/$pageId': {
      id: '/_dashboard/cms/$pageId'
      path: '/cms/$pageId'
      fullPath: '/cms/$pageId'
      preLoaderRoute: typeof DashboardCmsPageIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubmissionsRoute: typeof DashboardSubmissionsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCmsPageIdRoute: typeof DashboardCmsPageIdRoute
  DashboardCmsIndexRoute: typeof DashboardCmsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubmissionsRoute: DashboardSubmissionsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCmsPageIdRoute: DashboardCmsPageIdRoute,
  DashboardCmsIndexRoute: DashboardCmsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
